#!/bin/bash

# exit at first error
set -e

# where config folders will be copied
GLOBAL_INSTALL=/opt/mpi-is/pam # if install called by root
USER_INSTALL=$HOME/.mpi-is/pam # if install called by someone else

# not same installation folder if script called
# with or without sudo
if [ "$EUID" -ne 0 ]
then
   # without sudo: user home directory
   INSTALL_DIR=$USER_INSTALL
   echo "installing configuration file in $INSTALL_DIR"
else
   # with sudo: global install
   INSTALL_DIR=$GLOBAL_INSTALL
   echo "sudo: installing configuration file in $INSTALL_DIR"
fi

# creating the install folder
mkdir -p $INSTALL_DIR

# going into the config folder
cd config

# listing the folders to install as array
directories=($(ls -d */))

# installing each folder one by one
for folder in "${directories[@]}"
do
    # copying the content of the folder
    echo "- copying ${folder}"
    cp -r ./$folder $INSTALL_DIR
done

# setting permissions: everybody can read
# and execute
chmod -R 755 ${INSTALL_DIR}

exit 0

