#!/bin/bash

# exit at first error
set -e

# parse command line options
show_help()
{
>&2 cat << EOF
Install PAM configuration files.

Usage: ${0##*/} [--global]

Options:
  --global  Try to install globally even if not executed as root.
EOF
}
while :; do
    case $1 in
        -h|--help)
            show_help
            exit
            ;;
        --global)
            GLOBAL=1
            ;;
        ?*)
            >&2 echo -e "ERROR: Invalid argument '$1'.\n"
            show_help
            exit 1
            ;;
        *) # Default case: No more options, so break out of the loop.
            break
    esac
    shift
done

# where config folders will be copied
GLOBAL_INSTALL=/opt/mpi-is/pam # if install called by root
USER_INSTALL=$HOME/.mpi-is/pam # if install called by someone else

# select installation folder based on arguments and user id (always install
# globally when executed by root)
if [ "$EUID" -ne 0 ] && [ -z "$GLOBAL" ]
then
   # without sudo: user home directory
   INSTALL_DIR=$USER_INSTALL
   echo "installing configuration file in $INSTALL_DIR"
else
   # with sudo: global install
   INSTALL_DIR=$GLOBAL_INSTALL
   echo "sudo: installing configuration file in $INSTALL_DIR"
fi

# creating the install folder
mkdir -p $INSTALL_DIR

# going into the config folder
cd config

# listing the folders to install as array
directories=($(ls -d */))

# installing each folder one by one
for folder in "${directories[@]}"
do
    # copying the content of the folder
    echo "- copying ${folder}"
    cp -r ./$folder $INSTALL_DIR
done

# setting permissions: everybody can read
# and execute
chmod -R 755 ${INSTALL_DIR}

exit 0

